---
- name: install dnsmasq packages
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dnsmasq

- name: update /etc/dnsmasq.conf from template
  template:
    src: etc/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq

- name: ensure dnsmasq service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - dnsmasq
